DISTANCE_MATRIX =  "distancematrix/json?units={0}&origins={1}&destinations={2}&key=AIzaSyAJcN9JoeTZj4ZgkNcmwxkQr3kh65PBuRQ"
AUTO_COMPLETE=  "place/autocomplete/json?input={}&key=AIzaSyCBSvM5VkXIPQ8qATe-DewVCnOPAg1LfzQ&types=(cities)"
REVERSE_GEO_CODING= "geocode/json?latlng={0},{1}&key=AIzaSyB_kjjeVFyxXQE_IL6K1j33AwWWxtk1Y9E"
GEO_CODING= "geocode/json?address={0}&key=AIzaSyB_kjjeVFyxXQE_IL6K1j33AwWWxtk1Y9E"
PLACE_SEARCH_THINGS_TO_DO = "place/nearbysearch/json?location={0}&radius=5000&keyword=things%20to%20do%20in&rankby=prominence&key=AIzaSyCBSvM5VkXIPQ8qATe-DewVCnOPAg1LfzQ"
PLACE_SEARCH = "place/nearbysearch/json?location={0}&radius=5000&type={1}&rankby=prominence&key=AIzaSyCBSvM5VkXIPQ8qATe-DewVCnOPAg1LfzQ"
PLACE_DETAIL = "place/details/json?placeid={0}&key=AIzaSyCBSvM5VkXIPQ8qATe-DewVCnOPAg1LfzQ"
